Repository tsale/EDR-Telemetry, pull requests merged in 2023-04, with the labels that each got.

#19 Add Telemetry Generator Script & Config
  Telemetry-Generator/README.md
  Telemetry-Generator/config.json
  Telemetry-Generator/telemetry-generator.ps1
  Telemetry-Generator/telemetry-mappings.csv
Labels: enhancement

#5 adding Trellix EDR (mcafee)
  EDR_telem.json
Labels: enhancement, waiting for info

#18 ESET Inspect
  EDR_telem.json
Labels: enhancement

#15 Cybereason
  EDR_telem.json
Labels: enhancement, under review
