Repository tsale/EDR-Telemetry, pull requests merged in 2024-03, with the labels that each got.

#47 Add Cortex XDR based on public documentation
  EDR_telem.json
Labels: enhancement, under review

#42 Symantec SES Complete EDR
  EDR_telem.json
Labels: under review

#56 Table emoji update: Optimized for Color Blind Users
  README.md
  Tools/convert.py
Labels: enhancement
